### ISSUE TITLE
Discussion of TAP 4: The map file

### ISSUE THREAD

**Issue by vladimir-v-diaz** [theupdateframework/taps#33]
TAP 4 proposal is available at https://github.com/theupdateframework/taps/blob/master/tap4.md

Pull requests related to TAP 4:
https://github.com/theupdateframework/taps/pull/1
https://github.com/theupdateframework/taps/pull/2
https://github.com/theupdateframework/taps/pull/4
https://github.com/theupdateframework/taps/pull/5
https://github.com/theupdateframework/taps/pull/14
https://github.com/theupdateframework/taps/pull/15
https://github.com/theupdateframework/taps/pull/16

Discussion of TAP 4 on the TUF mailing list:
https://groups.google.com/d/msg/theupdateframework/gHOgkjxMpEU/mYw2CdxiBwAJ

**Comment by vladimir-v-diaz** [comment]
We decided to make a major change to TAP 4 where the map file is no longer required.  Instead, the TAP will now advise adopters on how they can support multiple repository consensus on entrusted targets.
For example, it shows how they can deal with prioritized repositories, terminating repositories, etc. and uses the map file as an example of how the reference implementation supported multiple repository consensus.

TAP 4's revision can be followed here:
https://github.com/theupdateframework/taps/pull/64

**Comment by vladimir-v-diaz** [comment]
@endophage

You requested that we make changes to TAP 4, namely to remove the map.json requirement.  Please let us know what you think of the [revised proposal](https://github.com/theupdateframework/taps/blob/master/tap4.md).

**Comment by vladimir-v-diaz** [comment]
I'd like to document here some of your requested changes...

> The only true security feature I see in TAP4 is the matching against multiple repos. Is there a way to greatly simplify the tap to focus on that specific feature? That focus would make it much clearer what it's actually trying to achieve.
> 
> If the TAP only contained the client side aliasing and not the multi-repo consensus, it would have no security benefits and be purely client side UX sugar. Would that get accepted as a TAP? IMO that falls squarely in the space of letting clients decide how best to interact with users and doesn't belong in the spec.
> 
> So is there a version of the TAP that only addresses multi-repo consensus? I envision something like the description of the update flow but covering updating from N repos and comparing targets between them. I would also like to see it go much deeper on detecting and handling the merging, or conflicts, within the Custom field. Is it OK for Custom to deviate at all across repos? Is it only OK as long as there are no conflicts? These are the kinds of things that should be addressed in this TAP if we want to fully answer what it means for 2 targets to be equivalent across repos.

**Comment by awwad** [comment]
Some time ago, we made a change to TAP 4 to ensure that the group of repositories in a single multi-repository delegation/mapping was ordered. We did this to allow a deterministic resolution if it turned out that multiple sets of repositories in the mapping, of size >= the mapping's threshold, agreed on different target info. While the new version of the TAP provides this ordered list, it does not specify the resolution to this issue in its steps: it doesn't tell you how to resolve this.

### Motivating Example:
Targets, including A.zip, are mapped to a multi-repository delegation with a threshold of 2 and the repository list [R1, R2, R3, R4, R5, R6, R7].

Client wants to obtain A.zip and reaches out to the repositories, which have different answers for the target info for A.zip:

R1: hash is 123...
R2: hash is 456...
R3: hash is 456...
R4: hash is 123...
R5: hash is 789...
R6: hash is 789...
R7: hash is 789...

In this scenario, the one thing made clear is that we go through the list of repositories in order. Here are four natural solutions to which targetinfo to accept:

#### Solution A:
The first **occurring** targetinfo that is vouched for by a threshold of repositories is the one with hash "123...". In order to conclude this, we had to either check every repository. (NB: There are a few **further** edge cases where you don't have to check **every** repo in this solution.)

#### Solution B:
The first targetinfo to **reach** threshold is the one with hash "456...", after we've checked R1, R2, and R3 (at which point we can stop).

#### Solution C:
After checking every repo, we can go with the one with the most repositories in agreement, and use the targetinfo with hash "789...". (Tie-breaking would then require Solution A or Solution B.)

#### Solution D:
Check every repository for metadata and accept all of the targetinfos above threshold ("123...", "456...", "789...") regardless of order. Then reach out to the repositories **in order** and validate the first target that matches any of those.

I'd argue against C or D. B requires the fewest repository checks, which is a virtue. A and B are otherwise hard for me to choose.

It is fair to deem this out of scope for the TUF spec, but then I think it remains important that implementers be aware of this ambiguity and choose a policy that is consistent. Different clients of a given system probably shouldn't have differing behavior in this regard. The argument against that is that even with the most deterministic strategies here, A and B, if repository R1 is down when we try refreshing, the answer changes and the client chugs right along using the targetinfo with hash "456..." using either strategy.

**Comment by mnm678** [comment]
As this TAP has been accepted, I propose we close this and move discussion to the [issue on the specification repository](https://github.com/theupdateframework/specification/issues/88).
