### ISSUE TITLE
Discussion of TAP 9: Mandatory metadata signing schemes

### ISSUE THREAD

**Issue by vladimir-v-diaz** [theupdateframework/taps#38]
TAP 9 proposal is available at https://github.com/theupdateframework/taps/blob/master/tap9.md

Pull requests related to TAP 9:
https://github.com/theupdateframework/taps/pull/21

**Comment by heartsucker** [comment]
There is one edge case here that was not discussed yet.

If the root wants to update its signing scheme, it has to generate a new key because there can only be one signature per key ID, and this would necessarily require duplicate signatures. It would, however, be possible if the root role in the new and old metadata has more keys than both thresholds.

**Comment by heartsucker** [comment]
Recommending we close this since it has been accepted.

**Comment by vladimir-v-diaz** [comment]
Closing TAP 9's discussion issue following its acceptance.
