### ISSUE TITLE
TAP 4/5 consolidation

### ISSUE THREAD

**Issue by ecordell** [theupdateframework/taps#8]
Unless I am misunderstanding something, I believe that with some slight modification TAP4 can completely encapsulate the functionality of TAP5.

In the example in TAP5, a new root file is generated that specifies a url for the root (hosted privately), and the PyPI-hosted Django delegation (targets) file is specified in the targets block, meaning that the targets file is pulled from the PyPI but the keys used to sign it are pinned by the privately-hosted root file.

I believe the same effect can be created with TAP4 alone. Could you not generate an alternate root that specifies only the Django keys in the targets file? This would still be privately held and hosted, and you would simply specify your private root in the `map.json` file. 

For example:

```javascript
{
  "repositories": {
    "Django": ["http://example.com/django/metadata"],
    "PyPI":   ["https://pypi.python.org/"]
  },
  "mapping": [
    {
      // django targets go through the privately-hosted root
      "paths":        ["*django*"],
      "repositories": ["Django", "PyPI"],
      "terminating":  false,
    },
    {
      // Map all other targets only to PyPI.
      "paths":        ["*"],
      "repositories": ["PyPI"]
    }
  ]
}
```

and the root file at `https://example.com/django/metadata/` has organization-supplied keys and pins to the Django project target keys?

Am I missing a fundamental difference between the two? If the only difference is that the snapshot doesn't list the root (so that roots can be swapped at will), couldn't that be specified by TAP4 as well? 

I'm also wondering if it would make sense to allow a mapping to point to a local file as well as a url, so that a user could pin a delegated set of keys by generating a root locally.

**Comment by trishankkarthik** [comment]
> Am I missing a fundamental difference between the two? If the only difference is that the snapshot doesn't list the root (so that roots can be swapped at will), couldn't that be specified by TAP4 as well?

Yes, I think there is a fundamental difference, and I may not have communicated it effectively.

TAP 5 allows one to restrict trust in a repository without hosting another repository (if the root metadata file is never to be updated at all). The root metadata file in TAP 5 allows a user to "reuse" the PyPI repository, but only to ever install and update the Django project.

Without TAP 5, the user would need to periodically copy the Django project metadata from PyPI, and host her own repository.

Does this make sense?

**Comment by ecordell** [comment]
> Without TAP 5, the user would need to periodically copy the Django project metadata from PyPI, and host her own repository.

To make sure I understand, you mean that the user would need to manually keep their snapshot/timestamp metadata in sync with PyPI?

> TAP 5 allows one to restrict trust in a repository without hosting another repository (if the root metadata file is never to be updated at all). The root metadata file in TAP 5 allows a user to "reuse" the PyPI repository, but only to ever install and update the Django project.

I think I understand now, but I have a suggestion. How about a change to the `mapped.json` file to allow different locations for different metadata?

```javascript
"repositories": {
    "Django": {
        "root": "https://djangoproject.com/metadata/root.json",
        "targets": "https://djangoproject.com/metadata/targets.json",
        "snapshot": "https://pypi.python.org/django/metadata/snapshot.json",
        "timestamp": "https://pypi.python.org/django/metadata/timestamp.json",
     },
    "PyPI":   ["https://pypi.python.org/"]
  },
```

I believe this provides the same functionality (a little more, I think - supposing you could also specify URLs for delegated roles) if you also allow local values?

The reason I suggest this is because I think there's a fairly large leap involved in TAP5: including URLs in signed, automatically-downloaded metadata. This opens up the attack surface quite a bit by allowing the server to instruct the client to make arbitrary http requests. Without the additions in TAP5, all domains that a client will hit can be enumerated ahead of time.

I also think this is a relatively small change in TAP4 to support what TAP5 does:

 - Remove root from snapshot
 - Allow different url per metatada file
 - Allow local locations as an alternative to remote locations

How does that sound? 

A nice side effect is that this also allows servers a little freedom in decided where to serve their metadata files (they don't have to all live in the same directory).

**Comment by JustinCappos** [comment]
So, I like the explicit mention of local locations instead of remote ones.
Somehow I was just thinking about 'none' providing this, but your
suggestion makes a lot more sense.

TAP 5 should already support different locations for different metadata.  I
think the written examples don't make that clear, but each top level role
has an optional field for a URL.

What you listed is an interesting suggestion and was one of the early
designs we thought about.  We decided on the TAP 5 design instead because
we thought there would be problems with key rotation for roles.  A
timestamp key may only live a few weeks.  So, by delegating to the root
(which then points to the key), you are not forced to change the
mapping.json file to keep it updated.

If you do want to force the key change, I think you can make your own root
that points to the timestamp, snapshot, etc.  Effectively, root just
becomes part of the mapping.json file then.

Does this argument change your mind?  What are your thoughts?

**Comment by ecordell** [comment]
> So, by delegating to the root (which then points to the key), you are not forced to change the mapping.json file to keep it updated.

Could you clarify the design choice to have URLs in the root rather than in the `mapping.json` file?  As far as I can tell this can be implemented with the same properties without changing the format of `root.json`.  

In the context of the example in TAP5, you wouldn't be forced to update `mapping.json` any time the timestamp key changed, though you would be forced to update your alternate root with the timestamp/snapshot keys from PyPI - but this is already a requirement of TAP5.

I think going with a full example might help illustrate my confusion. I'll use the example of Django/PyPI with a user that wishes to fix Django's delegated keys (i.e. the same scenario as described in TAP5). 

My organization, as in TAP5 example, hosts an alternate `root.json` at `http://example.com/metadata/root.json`.  This `root.json` is generated and looks like this:

```javascript
{
  "signed": {
    "roles": {
      "root": {
         // These keys are privately held by my organization, they did not come from PyPI
        "keyids": [...],
      },
      "timestamp": {
        // These keyids are the ones listed by PyPI for root
       "keyids": [...],
      },
      "snapshot": {
        // These keyids are the ones listed by PyPI for root
       "keyids": [...],
      },
      "targets": {
        // Use only the delegated targets role belonging to Django on PyPI.
        // These keyids are the ones listed by "https://pypi.python.org/metadata/delegations/Django.json" 
       "keyids": [...],
        ...
      },
      ...
    },
    ...
  },
  ...
}
```

This is essentially the same root file that is listed in TAP5, minus URLs, and shares the property: whenever keyids for the timestamp, snapshot, or targets role change on PyPI, this file must be updated to reflect those changes, and re-signed by the root keys listed.

As a user in my organization, I also generate a map file that looks like this:

```javascript
{
  "repositories": {
     "Django": [{
        // Point to my organization's private root
        "root": "http://example.com/metadata/root.json",
        // Look only in the delegated django role for matching targets
        "targets": "https://pypi.python.org/metadata/delegations/Django.json",
        // Use the default snapshot and timestamp from PyPI
        "snapshot": "https://pypi.python.org/django/metadata/snapshot.json",
        "timestamp": "https://pypi.python.org/django/metadata/timestamp.json",
     }],
     "PyPI":   ["https://pypi.python.org/"]
   },
  "mapping": [
    {
      "paths":        ["*django*"],
      "repositories": ["Django", "PyPI"],
      "terminating":  true,
    },
    {
      // Map all other targets only to PyPI.
      "paths":        ["*"],
      "repositories": ["PyPI"]
    }
  ]
}
```

This means that I pull my organization's root that pins Django project's keys, and consult it for any targets matching `*django*`

As far as I understand it, I have constructed a user story for the cases described by TAP5 using only a slightly modified `mapped.json` file from TAP4 - no changes to `root.json` format were necessary. 

Is this tracking or am I still missing something important? Thanks for being patient with me!

**Comment by JustinCappos** [comment]
Okay, thanks for the emails about this and sorry for the delay.  We're
hosting a major security conference and things are very hectic in general...

A few things I'd like to mention / discuss here:

1) I don't think it's likely that the URLs and keys will be able to be
separately updated.  After all, the URLs at a location are signed with one
set of keys.  I don't think it's likely you will have the same keys sign
many files at different locations.  (The only case I think this is likely
is when you just want to say "do not update this anymore", which can be
done either way.)  If you do have effectively a one-to-one mapping of keys
to URLs, it makes the most sense to me to have this all in one file.

2) I do see your points about knowing the http request points ahead of time
and not having redirects, etc. be possible.  I think the difference in the
attack susceptibility would come from a root role compromise where the
attacker cannot MITM or compromise the server storing data from the other
roles.  Is this the main scenario that concerns you?  The downside is that
now anytime a URL for content changes, every client must be manually
updated.  I'm concerned that this may happen fairly frequently, for example
in situations where the whole repo moves locations, perhaps due to an
upgrade to a newer repository...  I believe the latter situation is
immensely more likely and my current thinking is that the threat in this
case isn't likely enough to potentially harm usability.

What are your thoughts?  I'm glad this is stimulating discussion around
these issues.  It certainly has helped me crystalize some of my own
thinking.

**Comment by ecordell** [comment]
Summarizing our offline discussion for this:

- URLs in both `mapping.json` and `root.json` can be local files (`file://`)
- URLs in root improve the story around mirrors (save bandwidth)
- URLs not included in _all_ metadata so that there is less to consider security-wise

Did I miss anything?

**Comment by trishankkarthik** [comment]
On 5 December 2016 at 15:05, Evan Cordell <notifications@github.com> wrote:

> Summarizing our offline discussion for this:
>
>    - URLs in both mapping.json and root.json can be local files (file://)
>    - URLs in root improve the story around mirrors (save bandwidth)
>    - URLs not included in *all* metadata so that there is less to
>    consider security-wise
>
>
Nope, I think that's pretty good! Other changes are here:

https://github.com/theupdateframework/taps/commit/6a6609346938861af9ec59d07b5216a71c6f695f

With regarding to file:/// URLs --- in TAP 5, using an empty list of URLs
for a role denotes that its metadata file would never be updated remotely.
Does this get what you want, or did you have something else in mind? Sorry,
I may have misunderstood what you meant...

**Comment by ecordell** [comment]
> With regarding to file:/// URLs --- in TAP 5, using an empty list of URLs
for a role denotes that its metadata file would never be updated remotely.

Being able to specify a specific local file to use for metadata could be different from simply never updating it. For example, a local tuf repo performing an update should check the specified `file://` location in case the file has changed out of band. If the update process skipped updating it because of an empty URL list, it might assume the version it has in memory is still valid.

**Comment by trishankkarthik** [comment]
Oh, yeah, I see what you mean now. So you mean: a client should be able to update metadata on location X on disk using location Y also on disk.

So that is for the root metadata file. In a similar vein, should the list of mirrors in TAP 4 (the map file), also include ```file:///``` URLs to point to "domain names" (really, directories)?

**Comment by trishankkarthik** [comment]
I've clarified it [here](https://github.com/theupdateframework/taps/commit/05a02d3c2b98814eb7719858e353b929e0dda4e8)

**Comment by trishankkarthik** [comment]
By the way, if you are satisfied that TAPs 4 and 5 should be separate, could we close this issue? :)

**Comment by ecordell** [comment]
Yup, sounds good, thanks!
